project:
  type: website
  output-dir: _site

format:
  html:
    filters:
      - shinylive
    mainfont: "Times New Roman"
    highlight-style: a11y-light

website:
  page-navigation: true
  title: "HPM 883"
  description: "Homepage for HPM 883: Advanced Quantitative Methods for Health policy and Management"
  site-url: https://hpm883.github.io
  repo-url: https://github.com/hpm883
  repo-actions: [edit, issue]

  draft-mode: unlinked
 
  sidebar:
    background: "#F5F5F5"
    logo: images/logo.png
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/hpm883
        text: "GitHub"
      - icon: code-square
        href: https://rstudio.cloud/
        text: "Rstudio Cloud"
      - icon: life-preserver
        text: Support
        menu:
          - icon: person-raised-hand
            text: Office hours
            href: https://placeholder.link/office-hours
          - icon: people-fill
            text: Help from humans 
            href: https://placeholder.link/help-humans
          - icon: robot
            text: Help from AI (Chatbot)
            href: https://placeholder.link/chatbot
      - icon: slack
        href: https://hpm883.slack.com
        text: "Slack"
      - icon: file-check-fill
        text: "Canvas"
        menu:
          - icon: megaphone-fill
            text: Announcements
            url: https://placeholder.link/announcements
          - icon: file-arrow-up-fill
            text: Gradescope
            url: https://placeholder.link/gradescope
          - icon: alphabet-uppercase
            text: Gradebook
            url: https://placeholder.link/gradebook
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - index.qmd
      - section: "Course Information"
        contents:
          - href: course-overview.qmd
            text: "Overview"
          - href: course-syllabus.qmd
            text: "Syllabus"
          - href: instructors.qmd
            text: "Instructors"
          - href: course-communication.qmd
            text: "Communication"
      - section: "Semester Project"
        contents:
          - href: project.qmd
            text: "Project Description"
          - href: template-protocol.qmd
            text: "Template Protocol"
          - href: ex-simulate.qmd
            text: "Data Simulation Example"
      - href: resources.qmd
        text: "Resources"
      - href: computing.qmd
        text: "Computing"
      - section: "Unit 0: Foundations"
        contents:
          - href: unit-0/unit-0-foundations-1.qmd
            text: "Unit 0.0: Introduction"
          - href: unit-0/unit-0-foundations-2.qmd
            text: "Unit 0.1: A Field Experiment in Health Services Research"
          - href: unit-0/unit-0-foundations-3.qmd
            text: "Unit 0.2: Computing for Reproducible Research"
      - section: "Unit 1: Internal Validity"
        contents:
          - href: unit-1/unit-1-internal-1.qmd
            text: "Unit 1.0: Internal Validity"
          - href: labs/lab-1-InternalValidityPO.qmd
            text: "Lab 1: The Hospital of Uncertain Outcomes"
          - href: unit-1/unit-1-internal-2.qmd
            text: "Unit 1.1: Statistical Conclusion Validity"
          - href: labs/lab-2-Power.qmd
            text: "Lab 2: Power by Simulation"
      - section: "Unit 2: Design of Experiments"
        contents:
          - href: unit-2/unit-2-design-1.qmd
            text: "Unit 2.0: Optimal Experimental Design"
          - href: unit-2/unit-2-design-2.qmd
            text: "How to Randomize"

      

  page-footer:
    right: 'This page is built with [Quarto](https://quarto.org/).'
    left: "&copy; Copyright 2024, Sean Sylvia"
    background: "#F5F5F5"

theme:
  light: [cosmo, style/hpm883.scss]
  dark: [cosmo, style/hpm883-dark.scss]
linkcolor:: "#5D737E"
toc: true
code-copy: hover
code-link: true
code-overflow: wrap

execute:
  freeze: auto

editor: visual
