---
title: "Unit 4: Mechanisms"
draft: true
---

## Unit Overview

In this unit, we'll be digging deeper into analysis of randomized trials, focusing on the analysis of heterogeneous treatment effects and the role of moderators. We'll cover ways of thinking through the mechanisms of randomized trials as a way to guide data collection and analysis, and more technical details of how to estimate average treatment effects, heterogeneous treatment effects, and the role of moderators, using traditional methods and methods leveraging machine learning .

## Unit 4.0: Pre-analysis Plans

- [Project](project.qmd)
- [Pre-Analysis Plan Template](pre-analysis-plan-template.qmd)
- [Paying for Anemia Reduction Analysis Plan](https://www.socialscienceregistry.org/trials/1469)
- [Theory of Change Template](https://app.mural.co/t/digitalhealtheconlab8807/m/digitalhealtheconlab8807/1631664414562/d69f1bdcb404ff329601238e4b95383e9b667aff?sender=uef946b18ad7445100afd8329)
- [How to Build an UN-SILOED Theory of Change](https://www.youtube.com/watch?v=pWutrZwzP18)


## Unit 4.1: Average Treatment Effects


## Unit 4.2: Heterogeneous Treatment Effects


## Unit 4.3: Moderation



